syntax = "proto3";

package security.authz.v1;

option java_multiple_files = true;
option java_package = "com.bancoppel.security.auth.proto";
option java_outer_classname = "AuthzProto";

service TokenValidationService {
  rpc Validate (ValidateTokenRequest) returns (ValidateTokenResponse);
}

message Claim {
  string key = 1;
  string value = 2;
}

message ValidateTokenRequest {
  string accessToken = 1;
  repeated Claim claims = 2;
  string pathPrivateKey = 3;
}

message ValidateTokenResponse {
  string scopes = 1;
  repeated string permissions = 2;
  bool authenticated = 3;
  bool authorized = 4;
  string subject = 5;
  int64 expires = 6;
  string client = 7;
  string grantType = 8;
  string audience = 9;
  string error = 10;
  string message = 11;
}