syntax = "proto3";

package security.authz.v1;

import "google/protobuf/struct.proto";

option java_multiple_files = true;
option java_package = "com.bancoppel.security.auth.proto";
option java_outer_classname = "AuthzProto";

service TokenValidationService {
  rpc Validate (ValidateTokenRequest) returns (ValidateTokenResponse);
}

message ValidateTokenRequest {
  string accessToken = 1;
  map<string, google.protobuf.Value> claims = 2;
  string pathPrivateKey = 3;
}

message MetaValidateToken {
  string status = 1;
  int32 statusCode = 2;
  string timestamp = 3;
  string message = 4;
}

message DataValidateToken {
  bool authenticated = 1;
  bool authorized = 2;
  string jwt = 3;
  map<string,google.protobuf.Value> claims = 4;
}

message ValidateTokenResponse {
  MetaValidateToken meta = 1;
  DataValidateToken data = 2;
}